# Generated by Django 6.0.4 on 2026-04-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название путёвки')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('short_description', models.CharField(max_length=320, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('destination', models.CharField(max_length=150, verbose_name='Направление / страна')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена, ₽')),
                ('duration_days', models.PositiveSmallIntegerField(verbose_name='Длительность, дней')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата отправления')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/%Y/%m/', verbose_name='Фото обложки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Туристическая путёвка',
                'verbose_name_plural': 'Туристические путевки',
                'ordering': ['-created_at'],
            },
        ),
    ]
