# Generated by Django 6.0.4 on 2026-04-12 16:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='departure_city',
            field=models.CharField(default='Москва', help_text='Откуда вылет (для карты и описания).', max_length=120, verbose_name='Город вылета'),
        ),
        migrations.AddField(
            model_name='tour',
            name='dest_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта пункта назначения'),
        ),
        migrations.AddField(
            model_name='tour',
            name='dest_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота пункта назначения'),
        ),
        migrations.AddField(
            model_name='tour',
            name='origin_lat',
            field=models.FloatField(blank=True, help_text='Для карты (например Москва ≈ 55.76).', null=True, verbose_name='Широта точки вылета'),
        ),
        migrations.AddField(
            model_name='tour',
            name='origin_lng',
            field=models.FloatField(blank=True, help_text='≈ 37.62 для Москвы.', null=True, verbose_name='Долгота точки вылета'),
        ),
        migrations.AddField(
            model_name='tour',
            name='visa_note',
            field=models.TextField(blank=True, help_text='Дополнительно: срок действия паспорта, консульство и т.д.', verbose_name='Комментарий по визе'),
        ),
        migrations.AddField(
            model_name='tour',
            name='visa_status',
            field=models.CharField(choices=[('not_needed', 'Виза не требуется (по паспорту РФ)'), ('required', 'Нужна виза заранее'), ('on_arrival', 'Виза по прилёту / e-visa'), ('schengen', 'Нужен Шенген или виза ЕС')], default='not_needed', max_length=20, verbose_name='Виза'),
        ),
        migrations.CreateModel(
            name='HotelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отеля / размещения')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='Кратко')),
                ('stars', models.PositiveSmallIntegerField(default=3, verbose_name='Звёзд')),
                ('surcharge_per_person', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0 — входит в базовую цену путёвки.', max_digits=12, verbose_name='Доплата за чел., ₽')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок в списке')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_options', to='tours.tour', verbose_name='Путёвка')),
            ],
            options={
                'verbose_name': 'Вариант отеля',
                'verbose_name_plural': 'Варианты отелей',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество человек')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма путёвки, ₽')),
                ('hotel_surcharge_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Доплата за отели, ₽')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Итого к оплате, ₽')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tours.tour', verbose_name='Путёвка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('hotel_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tours.hoteloption', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
